#!/usr/bin/python

#!/usr/bin/env python
import subprocess

# 使用 subprocess 执行 git diff 命令获取未缓存和已缓存的变更文件
unstaged_files = subprocess.check_output(['git', 'diff', '--name-only']).decode('utf-8').splitlines()
staged_files = subprocess.check_output(['git', 'diff', '--cached', '--name-only']).decode('utf-8').splitlines()

# 合并两个列表以获取所有的变更文件
all_changed_files = unstaged_files + staged_files

# 打印所有变更文件
print("All changed files:")
for file in all_changed_files:
    if file.endswith(".java"):
        pass
    print(file)